manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: nicell
      url-base: https://github.com/nicell
  projects:
    - name: zmk
      remote: nicell
      revision: keycodes/f-keys-prsc
      import: app/west.yml
  self:
    path: config